# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
---
include:
  # The Dongle (XIAO)
  - board: seeeduino_xiao_ble
    shield: "cradio_dongle prospector_adapter"
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: prospector_dongle

  - board: seeeduino_xiao_ble
    shield: cradio_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: cradio_left

  - board: seeeduino_xiao_ble
    shield: cradio_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: cradio_right

  # Reset File for the Prospector Dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: reset_xiao_dongle

  # Reset File for the Ferris Halves
  - board: nrfmicro_13
    shield: settings_reset
    artifact-name: reset_nrfmicro_halves