# Screen brightness settings
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80

# Split Hub Settings
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Tell the dongle to look for 2 wireless halves
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Increase Bluetooth capacity for 2 halves + 3 computer profiles
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Enable the display for the Prospector
CONFIG_ZMK_DISPLAY=y